global:
  scrape_interval: 15s
  evaluation_interval: 15s

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

pushgateway:
  enabled: false

alertmanager:
  enabled: false

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
