apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp4dev
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smtp4dev
  template:
    metadata:
      labels:
        app: smtp4dev
    spec:
      containers:
        - name: smtp4dev
          image: rnwood/smtp4dev
          ports:
            - containerPort: 25
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: smtp4dev
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: smtp4dev
  ports:
    - name: smtp
      port: 25
      targetPort: 25
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30500
